In [3]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# print("x_train:", x_train, "x_test:", x_test)

model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10),
    ]
)

predictions = model(x_train[:1]).numpy()

print("predictions:", predictions)


predictions: [[ 0.22597876 -0.2944423  -0.31679162 -0.4647749  -0.17485368  0.8298224
   0.31240517  0.6265857   0.33221927 -0.8471129 ]]


In [4]:
tf.nn.softmax(predictions).numpy()

array([[0.10854764, 0.06450664, 0.06308095, 0.05440388, 0.07270113,
        0.1985484 , 0.11834638, 0.16203238, 0.12071468, 0.03711784]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

1.6167223

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0660 - accuracy: 0.9786
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0582 - accuracy: 0.9810
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0524 - accuracy: 0.9824
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0483 - accuracy: 0.9839
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0449 - accuracy: 0.9851


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0744 - accuracy: 0.9789 - 383ms/epoch - 1ms/step


[0.074350506067276, 0.9789000153541565]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.8009912e-07, 1.8456709e-09, 2.0497212e-06, 4.0769251e-04,
        1.1004892e-13, 3.9124036e-08, 3.6567097e-14, 9.9958533e-01,
        5.1556202e-07, 3.4905424e-06],
       [1.4011381e-14, 5.4519351e-06, 9.9999452e-01, 2.5730469e-09,
        1.9828554e-23, 2.1077282e-09, 1.4008436e-11, 2.0350792e-16,
        1.7260767e-11, 8.8868645e-19],
       [1.0199855e-08, 9.9970430e-01, 1.7133508e-04, 1.9360705e-06,
        3.3664805e-06, 1.1685386e-06, 4.4642493e-06, 1.0587779e-04,
        7.4280542e-06, 5.0873265e-08],
       [9.9995029e-01, 8.3107704e-10, 4.0460845e-06, 8.9396643e-08,
        1.7693523e-08, 3.6449173e-06, 3.7755599e-05, 3.3800723e-06,
        2.3409359e-09, 7.3280324e-07],
       [1.7261382e-07, 3.7647758e-12, 1.7135229e-06, 6.1029633e-11,
        9.9920624e-01, 7.1121553e-10, 9.4637620e-08, 1.3086787e-05,
        2.9746690e-08, 7.7879091e-04]], dtype=float32)>